language: java
jdk: oraclejdk8
sudo: false

cache:
  directories:
    - $HOME/.gradle

branches:
    only:
        - master
        - develop

install: ./gradlew setupCiWorkspace

script:
  - ./gradlew build
